name: WhisperLiveClient
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - ca-certificates=2025.2.25
  - libcxx=14.0.6
  - libffi=3.4.4
  - libopenblas=0.3.21
  - loguru=0.7.2
  - ncurses=6.4
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openssl=3.0.16
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - scipy=1.15.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - av==14.2.0
      - pyaudio==0.2.14
